Use attribute_missing instead of super
Using Rails 5, +super+ does not work and results in:

  NoMethodError: super: no superclass method `<attribute>=` ...

This change just copies
https://github.com/rails/rails/blob/v5.1.4/activemodel/lib/active_model/attribute_methods.rb#L431-L432
from +method_missing+.